services:
  - type: web
    name: ar4gpt
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
    autoDeploy: true
